name: Upload to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Upload .txt to Azure Blob Storage
      uses: bacongobbler/azure-blob-storage-upload@main
      with:
        source_dir: 'models'
        container_name: 'modelemotiondetection'
        connection_string: ${{ secrets.ACCESSKEY }}
        extra_args: '--pattern *.txt'
        overwrite: 'true'

    - name: Upload .params to Azure Blob Storage
      uses: bacongobbler/azure-blob-storage-upload@main
      with:
        source_dir: 'models'
        container_name: 'modelemotiondetection'
        connection_string: ${{ secrets.ACCESSKEY }}
        extra_args: '--pattern *.params'
        overwrite: 'true'